services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: railway
      MYSQL_ROOT_PASSWORD: rootpass
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: railway
      DB_USER: root
      DB_PASS: rootpass
      DJANGO_SECRET_KEY: dev-secret
      DEBUG: "True"
    depends_on:
      - db

volumes:
  db_data:
