# Generated by Django 4.2.21 on 2025-05-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_key', models.CharField(max_length=100, unique=True, verbose_name='参数键')),
                ('param_value', models.TextField(verbose_name='参数值')),
                ('param_type', models.CharField(choices=[('int', '整数'), ('float', '浮点数'), ('string', '字符串'), ('boolean', '布尔值'), ('json', 'JSON')], default='string', max_length=20, verbose_name='参数类型')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='参数描述')),
                ('is_editable', models.BooleanField(default=True, verbose_name='是否可编辑')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系统参数',
                'verbose_name_plural': '系统参数',
                'db_table': 'system_parameters',
            },
        ),
    ]
