# Generated by Django 4.2.21 on 2025-05-27 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingPile',
            fields=[
                ('pile_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('pile_type', models.CharField(choices=[('fast', '快充'), ('slow', '慢充')], max_length=10)),
                ('status', models.CharField(choices=[('normal', '正常'), ('fault', '故障'), ('offline', '离线')], default='normal', max_length=10)),
                ('is_working', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_duration', models.FloatField(default=0.0)),
                ('total_energy', models.FloatField(default=0.0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': '充电桩',
                'verbose_name_plural': '充电桩',
                'db_table': 'charging_pile',
            },
        ),
        migrations.CreateModel(
            name='ChargingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queue_number', models.CharField(max_length=20, unique=True)),
                ('charging_mode', models.CharField(choices=[('fast', '快充'), ('slow', '慢充')], max_length=10)),
                ('requested_amount', models.FloatField()),
                ('battery_capacity', models.FloatField()),
                ('current_status', models.CharField(choices=[('waiting', '等待中'), ('charging', '充电中'), ('completed', '已完成'), ('cancelled', '已取消')], default='waiting', max_length=10)),
                ('queue_position', models.IntegerField(default=0)),
                ('estimated_wait_time', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('current_amount', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charging_pile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charging.chargingpile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '充电请求',
                'verbose_name_plural': '充电请求',
                'db_table': 'charging_request',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('queue_update', '排队更新'), ('charging_start', '开始充电'), ('charging_complete', '充电完成'), ('pile_fault', '充电桩故障')], max_length=20)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('charging_amount', models.FloatField(default=0.0)),
                ('charging_duration', models.FloatField(default=0.0)),
                ('peak_hours', models.FloatField(default=0.0)),
                ('normal_hours', models.FloatField(default=0.0)),
                ('valley_hours', models.FloatField(default=0.0)),
                ('peak_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('normal_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valley_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charging.chargingpile')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='charging.chargingrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '充电会话',
                'verbose_name_plural': '充电会话',
                'db_table': 'charging_session',
            },
        ),
    ]
