# Generated by Django 4.2.21 on 2025-06-06 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vehicle_unique_default_vehicle_per_user'),
        ('charging', '0002_chargingpile_chargingrequest_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingrequest',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charging_requests', to='accounts.vehicle', verbose_name='车辆'),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charging_sessions', to='accounts.vehicle', verbose_name='车辆'),
        ),
    ]
