# Generated by Django 4.2.21 on 2025-06-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0004_add_multilevel_queue_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('queue_update', '排队更新'), ('charging_start', '开始充电'), ('charging_complete', '充电完成'), ('pile_fault', '充电桩故障'), ('queue_transfer', '转入桩队列'), ('charging_mode_change', '充电类型变更')], max_length=20),
        ),
    ]
